name: Build and Upload Frontend Docker Registry

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Git tag
        id: tag
        run: echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT   


      - name: Log in to Docker registry        
        run: docker login ${{vars.DOCKER_REGISTRY}} -u "${{ secrets.DOCKER_USERNAME }}" -p "${{secrets.DOCKER_PASSWORD}}"

      - name: Build and push image
        run: |
          docker build --no-cache -t ${{ vars.DOCKER_REGISTRY }}/ease-nexus-front:${{ steps.tag.outputs.tag }} .

          docker tag ${{ vars.DOCKER_REGISTRY }}/ease-nexus-front:${{ steps.tag.outputs.tag }} ${{ vars.DOCKER_REGISTRY }}/ease-nexus-front:latest

      - name: Push image to Docker registry
        run: |
          docker push ${{ vars.DOCKER_REGISTRY }}/ease-nexus-front:${{ steps.tag.outputs.tag }}
          docker push ${{ vars.DOCKER_REGISTRY }}/ease-nexus-front:latest

      - name: Update image tag in .env file
        run: |
          curl -X 'POST' \
            'https://lunalabs.com.br/api/compose.update' \
            -H 'accept: application/json' \
            -H 'Content-Type: application/json' \
            -H 'x-api-key: ${{ secrets.DOKPLOY_API_KEY }}' \
            -d '{
            "composeId": "wO-8IxjPXZGWIm1yeHGSG",  
            "env": "FRONTEND_DOMAIN=cbdg.demo.lunalabs.com.br\nIMAGE_TAG=${{ steps.tag.outputs.tag }}"
          }'

      - name: Trigger Proxy Refresh (optional)
        run: |
          curl https://lunalabs.com.br/api/deploy/compose/r1ubNFPoMypxuOuNbQrln